stages:
  - test
  - docker
  - nomad


build_image:
  only:
    - main
  stage: docker
  tags:
    - simonf
  script:
    - mkdir artifacts
    - docker build -t webserver-main .
    - docker tag webserver-main:latest https://git.de.geis-group.net/ZaricJ/nomad-deployment/webserver-main:latest
    - docker push git-registry.de.geis-group.net/skeleton:latest

deploy_docker_image:
  only:
    - main
  stage: nomad
  tags:
    - simonf
  script:
    - scp nginx-jovan.nomad devdeploy@10.50.2.45:~/nginx-jovan.nomad
    - ssh devdeploy@10.50.2.45 "nomad job run nginx-jovan.nomad"
    - ssh devdeploy@10.50.2.45 "rm -fv nginx-jovan.nomad"


